name: Deno

on:
    - push
    - pull_request

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repo
              uses: actions/checkout@v4

            - name: Set up Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x
                  cache: true

            - name: Check formatting
              run: deno fmt --check

            - name: Run linter
              run: deno lint

            - name: Run tests
              run: deno test --allow-all
